### ISSUE TITLE
Revisión de memoria y anexos

### ISSUE THREAD

**Issue by alvarag** [dbo1001/Gestor-TFG-2021#100]
Adjunto comentarios, revisa bien las tildes que tiendes a comértelas... No sé si tienes instalado bien el diccionario de TeXStudio para que te marque las faltas ortográficas.

[anexos_AAG.pdf](https://github.com/dbo1001/Gestor-TFG-2021/files/6305861/anexos_AAG.pdf) 

[memoria_AAG.pdf](https://github.com/dbo1001/Gestor-TFG-2021/files/6305860/memoria_AAG.pdf)

**Comment by dbo1001** [comment]
Vale, gracias. Ahora lo reviso.
