### ISSUE TITLE
Creación Release 0.6

### ISSUE THREAD

**Issue by dbo1001** [dbo1001/Gestor-TFG-2021#103]
Se creará la release 0.6 de la aplicación.

**Comment by dbo1001** [comment]
He realizado la release con la actualización de poder subir ficheros XLS. 
Al iniciar la app se utiliza la capa de datos que se especifica en el "config.properties" (ahora esta XLS) y al subir un fichero, ya sea csv o xls, se cambia las vistas a ese tipo de datos.
Cualquier problema al probarlo avisarme. @alvarag @clopezno

**Comment by clopezno** [comment]
@dbo1001 te paso algunas cuestiones que seguro que puedes solucionar

- No he encontrado el fichero .war  en la release https://github.com/dbo1001/Gestor-TFG-2021/releases/tag/0.6. Necesitamos ese fichero para poder probar la WebApp en un servidor de la UBU. Recuerda que lo tienes que adjuntar manualmente a la release. 

- He probado el enlace con el  despliegue en heroku que se proporciona en el fichero README y tampoco funciona https://gestor-tfg-2021.herokuapp.com/

- He comprobado que los commits están fallando en el proceso de integración continua https://github.com/dbo1001/Gestor-TFG-2021/commits/master. Entiendo que si hemos utilizado las action de Github es precisamente para verificar la integración correctamente. 

@alvarag en copia

**Comment by dbo1001** [comment]
Ya está solucionado.
Los test que están fallando son los del build.yml (los de SonarCloud) que es porque no está puesto bien. He desactivado ese workflows.

**Comment by alvarag** [comment]
No conseguimos desplegar el war, ¿tu has podido desplegarlo en casa y/o Heroku? Lo comento porque el error parece que es por temas de seguridad

**Comment by dbo1001** [comment]
Buenos días.

Si, en Heroku está desplegado y no me daba problemas. ¿Qué error os sale?

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________
