### ISSUE TITLE
Avances documentación

### ISSUE THREAD

**Issue by alvarag** [dbo1001/Gestor-TFG-2021#105]
Buenos días Diana, no sé si falta de hacer algún commit o realmente tienes la documentación un tanto "aparcada".

Te escribo la issue para que lo tengas en cuenta.

Saludos,

**Comment by dbo1001** [comment]
Buenas tardes. Apliqué los cambios que me sugeriste y he añadido alguna cosa más. Dentro de poco haré commit con los cambios que he hecho.
