### ISSUE TITLE
Creación release 0.8

### ISSUE THREAD

**Issue by dbo1001** [dbo1001/Gestor-TFG-2021#116]
Creación nueva release con el proyecto en su versión nueva (Vaadin 14)

**Comment by dbo1001** [comment]
Buenas noches @clopezno @alvarag

Perdonad por la tardanza, está creada la nueva Release. Cualquier problema o duda avisadme.

Un saludo, Gracias.

**Comment by alvarag** [comment]
Gracias, lo probamos.
