### ISSUE TITLE
Prueba de acceso de un Profesor

### ISSUE THREAD

**Issue by dbo1001** [dbo1001/Gestor-TFG-2021#167]
Se pedirá a alguno de los tutores que accedan a través del nuevo login con el moodle de UbuVirtual para verificar si ellos pueden acceder con la condición de que tengan permisos de actualización en la asignatura del TFG (los cuales yo no tengo)

**Comment by dbo1001** [comment]
Buenas noches @alvarag @clopezno.

¿Podéis acceder a la app desplegada en heroku y loguearos con vuestro email y contraseña de UbuVirtual, por favor? Es para verificar que el login funciona, ya que he puesto de condición que para acceder se tengan que tener permisos de actualización en la asignatura del Trabajo de Fin de Grado, los cuales yo no tengo. 

Un saludo, Gracias.

Link despliegue de Heroku --> https://gestor-tfg-2021.herokuapp.com/

**Comment by alvarag** [comment]
No, me ha dado fallo

![imagen](https://user-images.githubusercontent.com/9881614/120969239-35eb3580-c76a-11eb-86df-cea73cb6c586.png)

**Comment by dbo1001** [comment]
Puedes por favor ejecutar el comando:  `heroku logs --tail --app gestor-tfg-2021`

Es para ver los logs. Ese error sale cuando no puedes acceder a UbuVirtual, ya sea porque uno de los parámetros (email o contraseña) están mal , porque no existe o porque ha habido algún error al loggearse. Si sería a causa de los permiso debería salir un error diciendo que el usuario no tiene los permisos requeridos.

**Comment by alvarag** [comment]
No tengo el cliente de heroku instalado

**Comment by alvarag** [comment]
Yo creo que para la prueba lo mejor es que compruebes que el usuario esta registrado en TFG. Si con eso puedes registrate tu, ya vemos lo otro, pero primero confirmar que funciona el login

**Comment by dbo1001** [comment]
Sí, ya lo probé y funcionó. Quite la condición de que tuviese que tener los permisos de actualización para que me dejará acceder y pude entrar. Probé tanto con mi usuario, como con el de otra alumna que tiene esa asignatura.

**Comment by alvarag** [comment]
De acuerdo, pues mañana hacemos la prueba "en directo" con mi usuario o el de Carlos. Puedes probar a recoger el "rol" del usuario en el TFG y si es Profesor dejarle hacer cambios

**Comment by dbo1001** [comment]
Vale, bien. Mañana también podemos probar a daros acceso a mi pc con Teams que escribías vuestro correo y contraseña y veo los logs con mi pc, porque me parece raro ese error es como si no estuviese validando tu cuenta.
