### ISSUE TITLE
Realización de mejoras y correcciones en la memoria.

### ISSUE THREAD

**Issue by dbo1001** [dbo1001/Gestor-TFG-2021#187]
Se llevaran a cabo mejoras recomendadas por los tutores y se mejorará ciertos apartados incluyendo más información.

**Comment by alvarag** [comment]
Adjunto comentarios sobre memoria y anexos

[anexos_AAG.pdf](https://github.com/dbo1001/Gestor-TFG-2021/files/6765545/anexos_AAG.pdf)
[memoria_AAG.pdf](https://github.com/dbo1001/Gestor-TFG-2021/files/6765546/memoria_AAG.pdf)
