### ISSUE TITLE
Validar el fichero subido

### ISSUE THREAD

**Issue by alvarag** [dbo1001/Gestor-TFG-2021#27]
Actualmente la aplicación sube el fichero "csv" tal cual llega. Esto provoca que en caso de que el fichero tenga errores (de parseo) se quede en un estado "inconsistente" y deje de poderse utilizar la aplicación con un error que exige volver a cargar el war en el Tomcat.

Esto es algo muy importante que deberá ser tratado en el momento oportuno, lo dejo aquí para que no se nos olvide.

**Comment by dbo1001** [comment]
Vale, muchas gracias.
