### ISSUE TITLE
Añadir más extensiones a gitignore

### ISSUE THREAD

**Issue by alvarag** [dbo1001/Gestor-TFG-2021#65]
Para evitar que te suba el fichero "Thumbs.db" en las carpetas de imágenes, añadir ".db".

LaTeX crea muchos ficheros intermedios que tampoco deberían subirse: ".aux", ".log", ".bbl", ".blg", ".lof", ".lot"...

**Comment by dbo1001** [comment]
Entendido, gracias.

**Comment by alvarag** [comment]
No parece que te esté haciendo caso, si te fijas en https://github.com/dbo1001/Gestor-TFG-2021/tree/master/Documentacion/LaTeX siguen apareciendo ficheros .out, .blg...

**Comment by dbo1001** [comment]
Cierto, ahora lo miro. Gracias.
