### ISSUE TITLE
Page not found - Repositorios de proyectos no accesibles

### ISSUE THREAD

**Issue by dbo1001** [dbo1001/Gestor-TFG-2021#68]
Hay varios repositorios a los que no puedo acceder debido a que se ha eliminado o porque no tengo permiso.

**Comment by dbo1001** [comment]
Parece que el proyecto https://github.com/MarcosMillanTFG/GII-19.20--ASTI-CHALLENGE ya no existe, así que ¿dejo el proyecto sin analizar o qué puedo hacer?. Gracias.
 @alvarag @clopezno

**Comment by dbo1001** [comment]
Pasa lo mismo con el proyecto https://gitlab.com/HP-SCDS/Observatorio/2019-2020/ubu-smartenhancer

**Comment by dbo1001** [comment]
No tengo permiso para acceder al proyecto **[GII 19.36 Análisis predictivo de anomalías de AGVs](https://dev.azure.com/rdg-tfg/TFG)**.

![image](https://user-images.githubusercontent.com/44766510/112527858-c806b300-8da3-11eb-98c5-a349838aa8f9.png)

**Comment by dbo1001** [comment]
¿Dejo estos proyectos sin analizar o qué puedo hacer?. Gracias.
 @alvarag @clopezno

**Comment by clopezno** [comment]
Déjalos sin analizar. No hay problema.
Me imagino que son proyectos privados.

**Comment by dbo1001** [comment]
Perfecto, gracias.
